---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peso
  template:
    metadata:
      labels:
        app: peso
    spec:
      containers:
        - name: peso
          image: wandsbr/conversao-peso:v1
          ports:
            - containerPort: 80


